import test from "node:test";
import assert from "node:assert/strict";
import { demoCases } from "../public/demo-data.js";
const stages=["dataset","ep","ref","rga","context","tier","egp","sensor_ir","sensor_ll","oem_response","closure","assist_candidate"];
test("three sanitized robot and sensor REF cases provide every architecture stage",()=>{assert.deepEqual(demoCases.map(c=>c.id),["REF-LIDAR-2026-001","REF-CAMERA-2026-002","REF-IMU-2026-003"]);for(const c of demoCases){for(const stage of stages)assert.ok(c[stage]&&Object.keys(c[stage]).length,`${c.id} missing ${stage}`);assert.match(c.asset,/pseudonym/);assert.match(c.partner,/pseudonym/);}});
test("dataset, EP, and REF references remain connected",()=>{for(const c of demoCases){assert.equal(c.ref.dataset_reference,c.dataset.dataset_id);assert.equal(c.ref.ep_reference,c.ep.ep_id);assert.ok(c.ep.boundaries_seconds.includes(0));assert.equal(c.ep.case_reference,"WINPOL-DEFAULT-001");assert.notEqual(c.ref.ref_id,c.ep.case_reference);}});
test("claim, tier, recall, closure, and Vault boundaries are explicit",()=>{for(const c of demoCases){assert.match(c.ep.claim_boundary,/does not establish root cause/);assert.match(c.rga.boundary,/does not establish root cause/);assert.match(c.tier.boundary,/not a confirmed cause/);assert.equal(c.closure.root_cause_inferred,false);assert.match(c.closure.closure_status,/Not allowed/);assert.equal(c.assist_candidate.vault_eligibility,"Not eligible");assert.equal(c.assist_candidate.vault_write_status,"Not produced");}});
test("IR, LL, and OEM response remain distinct artifacts",()=>{for(const c of demoCases){assert.match(c.sensor_ir.artifact_id,/^IR-/);assert.match(c.sensor_ll.artifact_id,/^LL-/);assert.match(c.oem_response.artifact_id,/^OEMR-/);assert.notEqual(c.sensor_ir.artifact_id,c.sensor_ll.artifact_id);}});
test("EGP is explicitly pending official schema verification",()=>{for(const c of demoCases)assert.match(c.egp.claim_boundary,/field contract pending schema verification/);});
